[tools]
node = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:drizzle-kit" = "latest"
pnpm = "latest"
sqlite = "latest"

[env]
# GOOGLE_GENERATIVE_AI_API_KEYがセットされた.envファイルを使用
# これは、GoogleのGemini APIを使用するために必要です。
_.file = '.env'

[tasks.build]
description = "Build TypeScript to JavaScript"
run = "pnpm run build"

[tasks.cli]
description = "Run CLI interface"
run = "node dist/cli/index.js"
depends = ["build"]

[tasks.web]
description = "Start web development server"
run = "cd web && pnpm i && pnpm run dev"
depends = ["build"]

[tasks.web-build]
description = "Build web application for production"
run = "cd web && pnpm run build"
depends = ["build"]

[tasks.init]
description = "Initialize database"
run = "node dist/cli/index.js init"
depends = ["build"]

[tasks.migrate]
description = "Generate drizzle migration files"
run = "pnpm drizzle-kit generate"

[tasks.reset]
description = "Reset project - clean directories and reinitialize"
run = [
  "rm -rf drizzle dist knowledge",
  "pnpm i",
  "pnpm drizzle-kit generate", 
  "pnpm run build",
  "node dist/cli/index.js init"
]
